config/routes.rb
Rails.application.routes.draw do
  get 'members/index'
  get 'members/destroy'
  get 'invitations/index'
  get 'invitations/destroy'

  resources :member_requests
  resources :people
  resources :person_budget_notations
  resources :sub_budgets
  resources :sub_budget_notations
  get 'edit_sub_budget_notation/:id', to: 'sub_budget_notations_controller#edit'
  devise_for :users, :controllers => { :registrations => "user/registrations", :sessions => "sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :family_budgets, only: [:new, :create, :destroy, :show, :edit, :update]
  resources :user_budgets, only: [:create, :destroy]
  get 'search_user', to: 'users#search'
  get 'no_budget', to: 'home#nobudget'
  post 'add_user', to: "users#add_user"
  # post 'invite_user', to: "users#invite_user"
  post 'create_request', to: 'member_requests#create'
  post 'update_request', to: 'member_requests#update'
  post 'delete_request', to: 'member_requests#destroy'
  post 'create_invitation', to: 'invitations#create'
  post 'update_invitation', to: 'invitations#update'
  post 'delete_invitation', to: 'invitations#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :family_budget
  has_many :user_budgets
  has_many :family_budgets, through: :user_budgets
  has_many :member_requests, dependent: :destroy
  # has_many :invitations, dependent: :destroy
  has_many :pending_invitations, through: :invitations, source: :family_budget


  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end

  # Check if user has access to budget by beeing the creator, or a member through UserBudget.
  def owner_or_member_of_budget?
    # puts self.family_budgets.first.present?
    if self.family_budget.present?
      budget = FamilyBudget.find(self.family_budget.id)
    elsif self.family_budgets.first.present?
      budget = FamilyBudget.find(self.family_budgets.first.id)
    else
      budget = nil
    end
    return budget
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def exclude_if_has_budget(users)
    users.reject { |user| user.owner_or_member_of_budget? != nil }
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end
  
  def self.first_name_matches(param)
    matches('first_name', param)
  end
  
  def self.last_name_matches(param)
    matches('last_name', param)
  end
  
  def self.email_matches(param)
    matches('email', param)
  end
  
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def has_invitation?
    invitation = Invitation.find_by user_id: self.id
    true unless invitation == nil
  end

  def invitation
    invitation = Invitation.find_by user_id: self.id
    invitation
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  skip_before_action :user_has_budget?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :user_has_budget?
	def search
    if params[:search_param].blank?
      flash[:alert] = "You have entered an empty search string"
    else
      @users = User.search(params[:search_param])
      @users = current_user.except_current_user(@users)
      @users = current_user.exclude_if_has_budget(@users)
      flash[:alert] = "No users match this search criteria" if @users.blank?
    end
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end

  def add_user
    @budget = current_user.owner_or_member_of_budget?
    @user = User.find(params[:user])
		@user_budget = UserBudget.create(family_budget: @budget, user: @user)
		
    if @user_budget.save
      puts "User was successfully added"
    else
      puts "There was something wrong with the request"
    end  
    redirect_to root_path
  end

  # def invite_user
  #   @budget = current_user.owner_or_member_of_budget?
  #   @user = User.find(params[:user])
  #   @user_budget = UserBudget.create(family_budget: @budget, user: @user)
    
  #   if @user_budget.save
  #     puts "User was successfully added"
  #   else
  #     puts "There was something wrong with the request"
  #   end  
  #   redirect_to root_path
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_lookup.html.erb
<h3>Search for Users</h3>

  <%= form_tag search_user_path, remote: true, method: :get do %>
        <%= text_field_tag :search_param, params[:search_param], placeholder: "Enter name or email", autofocus: true, class: "" %>
        <%= button_tag(type: :submit, class: "") do %>
          Search
        <% end %>
  <% end %>
<div id="results">
  <%= render 'users/result' %>
</div>

app/views/users/_result.html.erb
<% if @users %>
  <% if @users.size > 0 %>
    <ul class="list-group">
          <% @users.each do |user| %>
            <li class="list-group-item">
              <strong>Name:</strong> <%= user.full_name %>
              <strong>Email:</strong> <%= user.email %>
              <% if !user.family_budgets.present? %>
                  <% if current_user.family_budget.present? %>
                    <%#= link_to "Add", add_user_path(user: user, family_budget: current_user.family_budget.id), class: "btn btn-primary btn-xs", method: :post %>
                    <%= link_to "Invite", create_invitation_path(user_id: user.id), class: "btn btn-primary btn-xs", method: :post %>
                  <% elsif current_user.family_budgets.present? %>
                    <%#= link_to "Add", add_user_path(user: user, family_budget: @family_budget), class: "btn btn-primary btn-xs", method: :post %>
                    <%= link_to "Invite", create_invitation_path(user_id: user.id), class: "btn btn-primary btn-xs", method: :post %>
                  <% end %>
              <% else %>
                User already added
              <% end %>
            </li>

          <% end %>
        </ul>
  <% end %>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = "<%= j (render 'users/result.html') %>";