config/routes.rb
Rails.application.routes.draw do
  get 'members/index'
  get 'members/destroy'
  get 'invitations/index'
  get 'invitations/destroy'

  resources :member_requests
  resources :people
  resources :person_budget_notations
  resources :sub_budgets
  resources :sub_budget_notations
  get 'edit_sub_budget_notation/:id', to: 'sub_budget_notations_controller#edit'
  devise_for :users, :controllers => { :registrations => "user/registrations", :sessions => "sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :family_budgets, only: [:new, :create, :destroy, :show, :edit, :update]
  resources :user_budgets, only: [:create, :destroy]
  get 'search_user', to: 'users#search'
  get 'no_budget', to: 'home#nobudget'
  post 'add_user', to: "users#add_user"
  # post 'invite_user', to: "users#invite_user"
  post 'create_request', to: 'member_requests#create'
  post 'update_request', to: 'member_requests#update'
  post 'delete_request', to: 'member_requests#destroy'
  post 'create_invitation', to: 'invitations#create'
  post 'update_invitation', to: 'invitations#update'
  post 'delete_invitation', to: 'invitations#destroy'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :user_has_budget?, only: :nobudget
	def index
		@family_budgets = FamilyBudget.all
		if !current_user.family_budget.present? && !current_user.family_budgets.present?
			redirect_to no_budget_path
			return
		end
		@sub_budgets = current_user.owner_or_member_of_budget?.sub_budgets
		@new_sub_budget_notation = SubBudgetNotation.new
		@people = current_user.owner_or_member_of_budget?.people
		@new_person_budget_notation = PersonBudgetNotation.new
	
	end

	def nobudget
		@family_budget = current_user.owner_or_member_of_budget?
		@family_budgets = FamilyBudget.all
		if @family_budget == nil
			puts "\nNo Budget\n\n"
			query_params = request.query_parameters
			puts query_params[:finished]
			if query_params[:finished]
				user = User.find(current_user.id)
				user.first_time = false
				user.save
				return redirect_to root_path
			end
			render "nobudget"
		else
			redirect_to root_path
		end
	end
		
		
end

app/views/home/_information.html.erb
<div class="col-md-4">
	<div class="card card-info">
	  <div class="header">
	    <h4 class="title">Information</h4>
	    <%= link_to "Edit Family Budget", edit_family_budget_path(id: current_user.owner_or_member_of_budget?.id ), class: "btn btn-default btn-xs", method: :get %>
	    <%= link_to "People Overview", people_path, class: "btn btn-default btn-xs", method: :get %>
	  </div>
	  <div class="content info-content">
	  	<div class="people">
	  		<div class="list-group">
	  		<% if !@people.present?%>
	  			<h5>There is currently not added any <strong>People</strong> to this Budget.</h5>
	  			<p>When you have added People to the Family Budget you can link <em>outgoing Budget Notations</em> from them to <em>incomming Budget Notations</em> on a <strong>Sub Budget</strong>.</p>
	  			<%= link_to "Add People", new_person_path, class: "btn btn-primary", method: :get %>
				<% else %>
					<h5>People in this Budget</h5>
	  			<div class="list-group person">
					<% @people.each do |person| %>    
					  <li href="#" class="list-group-item">
					    <h4 class="list-group-item-heading"><%= person.name %></h4>
					    <p class="list-group-item-text"><strong>Funds:</strong><%= person.total_in %></p>
					    <p class="list-group-item-text"><strong>Out: </strong><%= person.total_out %></p>
					    <p class="list-group-item-text"><strong>Rest: </strong><%= person.rest %></p>
					  </li>
			  	<% end %>
			  	</div>
				<% end %>
	  	</div>
		  </div>
		</div>
	</div>
</div>

<div class="col-md-4">
	<div class="card">
		<div class="header">
		    <h4 class="title">Outgoing from Family Budget</h4>
		    <p class="category">Combined from all Sub Budgets</p>
		</div>
		<div class="content">
		    <div id="chartPreferences" class="ct-chart ct-perfect-fourth">
		    	<% if !current_user.owner_or_member_of_budget?.hasOutgoingNotations? %>
						<h4>You dont have any Sub budgets.</h4>
						<p>This will show a simple graph of your outgoing Sub Budget Notations.</p>
		    	<% end %>
		    </div>

		    <div class="footer">
		        <div class="legend">
		            
		        </div>
		        <hr>
		        <div class="stats">
		            <i class="fa fa-clock-o"></i> Updates on refresh
		        </div>
		    </div>
		</div>
	</div>

	<script>
		var allNotations = '<%= current_user.owner_or_member_of_budget?.getAllNotations %>';
		// console.log(JSON.parse(allNotations));
		chart.makePieChart(JSON.parse(allNotations))
	</script>
</div>

 <div class="col-md-4">
 	<div class="card">
		<div class="header">
		    <h4 class="title">Stats</h4>
		    <p class="category">Last Campaign Performance</p>
		</div>
		<div class="content">
			<div class="list-group">
				<li class="list-group-item">
					<strong>Total in to budget: </strong><%= current_user.owner_or_member_of_budget?.total_in_to_budget %>
					</li>
				<li class="list-group-item">
					<strong>Total out from budget: </strong><%= current_user.owner_or_member_of_budget?.total_out_from_budget %>
				</li>
				<li class="list-group-item">
					<strong>Balance: </strong><%= current_user.owner_or_member_of_budget?.balance %>
				</li>
				<%#= current_user.family_budget.getAllNotations %>
			</div>
		</div>
	</div>
</div>
	

app/views/home/_people.html.erb
<% if @people.empty? %>
  <div class="card">
    <div class="header">
      <h4 class="title">No Sub Budgets</h4>
    </div>
    <div class="content">
      <table class="table table-striped table-condensed">
              <thead>
                  <tr>
                    <th scope="col">Title</th>
                    <th scope="col" class="hidden-sm hidden-xs">Description</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Type</th>
                    <th scope="col">Action</th>              
                  </tr>
                </thead>
                <tbody>
                <%= render "home/peoplebudgetnotation",  sb: @sub_budgets.first %>

              <% end %>
            </tbody>
            
          </table>
    </div>
  </div>
<% end %>

app/views/home/_peoplebudgetnotation.html.erb
<% sb.sub_budget_notations.each do |pbn| %>
	<tr data-id="<%= sbn.id %>" class="type-<%= pbn.notation_type %>">
	  <th scope="row"><%= pbn.title %></th>
	  <td class="hidden-sm hidden-xs""><%= pbn.description %></td>
	  <td><%= pbn.amount %></td>
	  <td>
	  	<%#= link_to "Edit", edit_sub_budget_notation_path(id: pbn.id), remote: true, class: "btn btn-primary btn-xs", "data-toggle" => "modal", "data-target" => "#myModal" %>
			<%#= link_to "Delete", sub_budget_notation_path(id: pbn.id), remote: true, class: "btn btn-danger btn-xs",method: :delete %>
	  </td>
	</tr>
<% end %>

app/views/home/_search.html.erb
<div class="col-md-12">
	<div class="card card-info">
		<div class="header">
			<h4 class="title">Invite other members to this Family Budget</h4>
		</div>
		<div class="content">
			<%= form_tag search_user_path, remote: true, method: :get do %>
				<%= text_field_tag :search_param, params[:search_param], placeholder: "Enter name or email", autofocus: true, class: "" %>
				<%= button_tag(type: :submit, class: "") do %>
					Search
				<% end %>
			<% end %>
			<div id="results">
				<%= render 'users/result' %>
			</div>
		</div>
	</div>
</div>

<% if current_user.family_budget.present? && current_user.family_budget.pending_members.present? %>
<div class="col-md-12 hidden-md hidden-lg">
	<div class="card card-info">
		<div class="header">
			<h4 class="title">Users who want to join</h4>
		</div>
		<div class="content">
			<ul class="list-group">
			  <% current_user.family_budget.pending_members.each do |request| %>
			      <li class="list-group-item">
			        <%= link_to update_request_path(request: request, budget: current_user.family_budget.id, user_id: request.id), remote: true,  method: :post  do %>
			          <%= request.email %> want to join your Budget!
			        <% end %>
			      </li>
			    <% end %>
			  </ul>
		</div>
	</div>
</div>
<% end %>	

app/views/home/_subbudget.html.erb
<% if !@sub_budgets.present? %>
  <div class="card">
    <div class="header">
      <h4 class="title">No Sub Budgets</h4>
    </div>
    <div class="content">
      <%= link_to "Create Sub Budget", new_sub_budget_path, class: "btn btn-default btn-lg", method: :get %>
    </div>
  </div>
<% else %>
    <% @sub_budgets.each do |sb| %>
    <% if controller_name != "sub_budgets" %>
      <small>To add more sub budgets, go to <%= link_to "sub budget home", sub_budgets_path, method: :get %>.</small>
    <% end %>
  <div class="card ">
      <div class="header">
          <h4 class="title"><%= sb.title %></h4>
          <p class="category"><%= sb.description %></p>
          <p class="category-info"><strong>Inn:</strong> <%= sb.incomming %></p>
          <p class="category-info"><strong>Out:</strong> <%= sb.outgoing %></p>
          <p class="category-info"><strong>Balance: </strong><%= sb.balance %></p>
          <%= link_to "Delete", sub_budget_path(id: sb.id), class: "btn btn-danger btn-sm", method: :delete %>
          <%= link_to "Edit", edit_sub_budget_path(id: sb.id), class: "btn btn-default btn-sm", method: :get %>
      </div>
      <div class="content">
        <small id="pbn-info-message">Incomming notations from a person can be linked to <%= link_to "this perosn", people_path, method: :get %>.</small>
              <% if !sb.sub_budget_notations.first.present? %>
                <p class="mb-5">No Notations.</p>
                <%= render "sub_budget_notations/new", sb: sb %>
              <% else %>
              <%= render "sub_budget_notations/new", sb: sb %>
              <table class="table table-striped table-condensed">
              <thead>
                  <tr>
                    <th scope="col">Title</th>
                    <th scope="col" class="hidden-sm hidden-xs">Description</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Action</th>              
                  </tr>
                </thead>
                <tbody>
                <%= render "home/subbudgetnotation",  sb: sb %>
              <% end %>
            </tbody>
            
          </table>
      </div>
  </div>
  <% end %>
<% end %>

app/views/home/_subbudgetnotation.html.erb
<% sb.sub_budget_notations.each do |sbn| %>
	<tr data-id="<%= sbn.id %>" class="type-<%= sbn.notation_type %>">
	  <td><%= sbn.title %></td>
	  <td class="hidden-sm hidden-xs""><%= sbn.description %></td>
	  <td class=""><%= sbn.amount %></td>
	  <td>
	  	<%= link_to "Edit", edit_sub_budget_notation_path(id: sbn.id), remote: true, class: "btn btn-primary btn-xs", "data-toggle" => "modal", "data-target" => "#myModal" %>
			<%= link_to "Delete", sub_budget_notation_path(id: sbn.id), remote: true, class: "btn btn-danger btn-xs",method: :delete %>
	  </td>
	</tr>
<% end %>

app/views/home/index.html.erb
                  <div class="page-header">

                    <h1><%= current_user.owner_or_member_of_budget?.name %></h1>
                    <p><%= current_user.owner_or_member_of_budget?.description %></p>
                    
                  </div>

                  <div class="row">
                  	
                  	<%= render "home/search" %>

                  </div>
                  
                  <div class="row">
                    
                      <%= render "home/information" %>
                      
                  </div>

                  <div class="row">
                      <div class="col-md-12">
                        
                          <%= render "home/subbudget" %>  
                        
                      </div>
                  </div>
                  

app/views/home/nobudget.html.erb
<div class="row">
	
	<div class="col-md-12">
		<% if !current_user.family_budget.present? && !current_user.family_budgets.present?%>

			<h2>Welcome to <em>Family Budget</em></h2>
			<p>Family Budget is a static overview of your familys budget. Displaying your income and expenses over a periode of your choice.</p>

			<div id="start-info">
				<div class="panel panel-default">
				  <div class="panel-body">
				    Create a <strong>Family Budget</strong>. You could look at this as a container for your budget.
				  </div>
				</div>
				<div class="panel panel-default">
				  <div class="panel-body">
				    Create resonable <strong>Sub Budgets</strong>. This could be groceries, utilities, car-budget and so on.
				  </div>
				</div>
				<div class="panel panel-default">
				  <div class="panel-body">
				    Create the <strong>People</strong> involved in your Family Budget.
				  </div>
				</div>
			</div>

			<p>So now you need a budget. Either create one, send a member request to join one, or wait for an invitation.</p>
			<%= link_to "Create Budget", new_family_budget_path, class: "btn btn-primary btn-lg center-block", id: "create-budget", method: :get %>
			<% if !current_user.member_requests.present? %>
				<% if current_user.first_time %>
					<div class="card" id="dummy-request">
				    <div class="header">
				      <h4 class="title">Request to join a friends budget</h4>
				    </div>
				    <div class="content">
							<ul class="list-group">
									<li class="list-group-item">
										<h4 class="list-group-item-heading">BUDGET NAME</h4>
										<p class="list-group-item-text">
											<strong>Owned by: </strong> OWNER NAME
										</p>
										<span>
											<%= link_to "Request membership", no_budget_path(:finished => 'true'), class: "btn btn-primary btn-xs", method: :get %>
										</span>
									</li>
								</ul>
						</div>
					</div>

				<% elsif FamilyBudget.first.present? %>
					
					<div class="card">
				    <div class="header">
				      <h4 class="title">Request to join a friends budget</h4>
				    </div>
				    <div class="content">
							<ul class="list-group">
								<% @family_budgets.each do |budget| %>
									<li class="list-group-item">
										<h4 class="list-group-item-heading"><%= budget.name %></h4>
										<p class="list-group-item-text">
											<strong>Owned by: </strong> <%= budget.owner_of_budget %>
										</p>
										<span>
											<%= link_to "Request membership", create_request_path(budget_id: budget.id), class: "btn btn-primary btn-xs", method: :post %>
										</span>
									</li>
								<% end %>
								</ul>
						</div>
					</div>
				<% else %>
					<h3>Request to join a budget.</h3>
					<p>There does not seem to exist any Family Budgets. I guess your the first person here..</p>
				<% end %>
			<% else %>
			<div class="card">
		    <div class="header">
		      <h4 class="title">You have a pending request</h4>
		    </div>
		    <div class="content">
		    	<p><strong>Budget name:</strong> <%= current_user.member_requests.first.family_budget.name %></p>
		    	<small><strong>Budget owner:</strong></small> <%= current_user.member_requests.first.family_budget.owner_of_budget %>
				<%= link_to "Cancel request", delete_request_path(user_id: current_user.id), class: "btn btn-primary", method: :post %>
				</div>
			</div>
			<% end %>
			<% if current_user.has_invitation? %>
				<div class="card">
			    <div class="header">
			      <h4 class="title">You have an invitation to a budget!</h4>
			    </div>
			    <div class="content">
			    	<p><strong>Budget name:</strong> <%= current_user.invitation.family_budget.name %></p>
			    	<p><small><strong>Budget owner:</strong></small> <%= current_user.invitation.family_budget.owner_of_budget %></p>
					<%= link_to "Join", update_invitation_path(budget_id: current_user.invitation.family_budget.id), class: "btn btn-primary btn-xs", method: :post %>
					</div>
				</div>
			<% elsif current_user.first_time %>
				<div class="card" id="dummy-invitation">
			    <div class="header">
			      <h4 class="title">You have an invitation to a budget!</h4>
			    </div>
			    <div class="content">
			    	<p><strong>Budget name:</strong> TO SOME BUDGET</p>
			    	<p><small><strong>Budget owner:</strong> NAME OF SOME OWNER</small></p>
					<%= link_to "Join", no_budget_path(:finished => 'true'), class: "btn btn-primary btn-xs", method: :get %>
					</div>
				</div>
			<% else %>

			<% end %>
		<% end %>
		<input id="first-time" type="hidden" name="first-time" data-first="<%= current_user.first_time %>">
	</div>
</div>