config/routes.rb
Rails.application.routes.draw do
  get 'members/index'
  get 'members/destroy'
  get 'invitations/index'
  get 'invitations/destroy'

  resources :member_requests
  resources :people
  resources :person_budget_notations
  resources :sub_budgets
  resources :sub_budget_notations
  get 'edit_sub_budget_notation/:id', to: 'sub_budget_notations_controller#edit'
  devise_for :users, :controllers => { :registrations => "user/registrations", :sessions => "sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :family_budgets, only: [:new, :create, :destroy, :show, :edit, :update]
  resources :user_budgets, only: [:create, :destroy]
  get 'search_user', to: 'users#search'
  get 'no_budget', to: 'home#nobudget'
  post 'add_user', to: "users#add_user"
  # post 'invite_user', to: "users#invite_user"
  post 'create_request', to: 'member_requests#create'
  post 'update_request', to: 'member_requests#update'
  post 'delete_request', to: 'member_requests#destroy'
  post 'create_invitation', to: 'invitations#create'
  post 'update_invitation', to: 'invitations#update'
  post 'delete_invitation', to: 'invitations#destroy'
end

app/models/person_budget_notation.rb
class PersonBudgetNotation < ApplicationRecord
  belongs_to :person
  belongs_to :sub_budget, optional: true
  # belongs_to :sub_budget_notation, optional: true, dependent: :destroy
  validates :notation_type, :amount, presence: true
  validates :notation_type, format: { with: /deposit|withdrawal/, message: "must be deposit or withdrawal" }
end

app/controllers/person_budget_notations_controller.rb
class PersonBudgetNotationsController < ApplicationController

	def index

	end

	def new
		@person_budget_notation = PersonBudgetNotation.new
		@family_budget = current_user.owner_or_member_of_budget?
	end

	def create

		@person_budget_notation = PersonBudgetNotation.new(person_budget_notation_params)
		createSubBudgetNotation = false
		sub_budget = ""
		this_sub_budget_id = ""

		# Set SubBudgetId if it exists
		if person_budget_notation_params["sub_budget_id"].present?
			createSubBudgetNotation = true
			sub_budget = SubBudget.where("title like ?", person_budget_notation_params["sub_budget_id"])
			this_sub_budget_id = sub_budget.first.id
			@person_budget_notation.sub_budget_id = this_sub_budget_id
		end

		if @person_budget_notation.save
			respond_to do |format|
      	format.json { render :json => @person_budget_notation }
      	format.js
   		end
   		flash[:notice] = "Notation has been created!"
   	else
   		alertMessage = "Notation was not created! "
   		if @person_budget_notation.errors.messages
   			if @person_budget_notation.errors.messages[:notation_type].present?
   				alertMessage += "You need to specify if it is inn or out. "
   			end
   			if @person_budget_notation.errors.messages[:amount].present?
   				alertMessage += "You need to specify an amount."
   			end
   			puts @person_budget_notation.errors.messages
   		end
   		flash[:alert] = alertMessage
		end

		# Create SubBudgetNotation..
		if createSubBudgetNotation
								
			SubBudgetNotation.create(sub_budget_id:this_sub_budget_id, 
				title:"From #{@person_budget_notation.person.name}", 
				description: person_budget_notation_params["title"], 
				amount:person_budget_notation_params["amount"], 
				notation_type:"deposit",
				person_budget_notation_id: @person_budget_notation.id)
		end

	end

	def edit
		@person_budget_notation = PersonBudgetNotation.find(params[:id])
	end

	def update
		@person_budget_notation = PersonBudgetNotation.find(params[:id])

		if @person_budget_notation.sub_budget_id != nil
      @sub_budget_notation = SubBudgetNotation.where("person_budget_notation_id like ?", @person_budget_notation.id)
    end

		if @person_budget_notation.update(person_budget_notation_params)
			respond_to do |format|
      	format.json { render :json => @person_budget_notation }
      	format.js
   		end
   		flash[:notice] = "Notation has been edited!"
		else
			alertMessage = "Notation was not created! "
   		if @person_budget_notation.errors.messages
   			if @person_budget_notation.errors.messages[:notation_type].present?
   				alertMessage += "You need to specify if it is inn or out. "
   			end
   			if @person_budget_notation.errors.messages[:amount].present?
   				alertMessage += "You need to specify an amount."
   			end
   			puts @person_budget_notation.errors.messages
   		end
   		flash[:alert] = alertMessage
		end

		if @sub_budget_notation != nil
			@sub_budget_notation.update(amount: person_budget_notation_params["amount"])
			puts "Sub Budget Notation also updated"
		end
	end

	def destroy
		@person_budget_notation = PersonBudgetNotation.find(params[:id])
		@sub_budget_notation = SubBudgetNotation.where("person_budget_notation_id like ?", params[:id]).first
		if @person_budget_notation.destroy
		 respond_to do |format|
      	format.json { render :json => @person_budget_notation }
      	format.js
   		end
   		@sub_budget_notation.destroy
   		flash[:alert] = "Notation was deleted!"
   	else
   		flash[:alert] = "Notation could NOT be deleted!"
   	end

   	


	end

	private

	def person_budget_notation_params
    params.require(:person_budget_notation).permit(:title, :description, :amount, :notation_type, :person_id, :sub_budget_id)
  end
end

app/helpers/person_budget_notations_helper.rb
module PersonBudgetNotationsHelper
end

app/views/person_budget_notations/_form.html.erb
<%= form_for @person_budget_notation, :html => { :class => "form-inline" }, remote: true do |f| %>
		<div class="form-group">
			<%= f.label :title, class: "sr-only" %>
			<%= f.text_field :title, class: "form-control", placeholder: "Title" %>

			<%= f.label :description, class: "sr-only" %>
			<%= f.text_field :description, class: "form-control hidden-sm hidden-xs", placeholder: "Description" %>

			<%= f.label :amount, class: "sr-only" %>
			<%= f.text_field :amount, class: "form-control", placeholder: "Amount" %>

			<%= f.radio_button :notation_type, "deposit", class: "form-control radio-inline" %>
			<%= f.label :notation_type, "Inn" %>
			<%= f.radio_button :notation_type, "withdrawal", class: "form-control radio-inline" %>
			<%= f.label :notation_type, "Out" %>
		</div>
		<div class="form-group">
			<%= f.submit "Update", class: "btn btn-default btn-xs" %>
			<button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Close</button>
		</div>
	</div>
<% end %>

app/views/person_budget_notations/_new.html.erb
<%= form_for @new_person_budget_notation,  :html => { :class => "form-inline" }, remote: true do |f| %>

		<div class="form-group">
			<%= f.label :title, class: "sr-only" %>
			<%= f.text_field :title, class: "form-control", placeholder: "Title" %>

			<%= f.label :description, class: "sr-only" %>
			<%= f.text_field :description, class: "form-control hidden-sm hidden-xs", placeholder: "Description" %>

			<%= f.label :amount, class: "sr-only" %>
			<%= f.number_field :amount, class: "form-control", placeholder: "Amount" %>

			<%= f.radio_button :notation_type, "deposit", checked: true, class: "form-control radio-inline", id: "deposit" %>
			<%= f.label :notation_type, "Inn" %>
			<%= f.radio_button :notation_type, "withdrawal",  class: "form-control radio-inline", id: "withdrawal" %>
			<%= f.label :notation_type, "Out" %>
		</div>

		<div class="form-group hidden" id="select-group">
			<%= f.select( :sub_budget_id, options_for_select(budget.sub_budgets.map {|sb| sb.title }), prompt: "Transfer to a sub budget?" ) %>
		</div>
		
		<div class="form-group">
			<%= f.hidden_field :person_id, :value => p.id %>
			<%= f.submit "Add", class: "btn btn-primary btn new-btn" %>
		</div>

<% end %>

app/views/person_budget_notations/_pbn.html.erb
<% p.person_budget_notations.each do |pbn| %>
	<tr data-id="<%= pbn.id %>" class="type-<%= pbn.notation_type %>">
	  <td><%= pbn.title %></th>
	  <td class="hidden-sm hidden-xs""><%= pbn.description %></td>
	  <td><%= pbn.amount %></td>
	  <td>
	  	<%= link_to "Edit", edit_person_budget_notation_path(id: pbn.id), remote: true, class: "btn btn-primary btn-xs", "data-toggle" => "modal", "data-target" => "#myModal" %>
			<%= link_to "Delete", person_budget_notation_path(id: pbn.id), remote: true, class: "btn btn-danger btn-xs",method: :delete %>
	  </td>
	</tr>
<% end %>

app/views/person_budget_notations/create.js.erb
var flash = createFlashMessage('<%= j flash[:notice] %>', '<%= j flash[:alert] %>');

$.notify({
    icon: 'pe-7s-flag',
    message: flash.message

  },{
      type: flash.messageType,
      timer: 500
});

var formInputs = document.querySelectorAll('.form-control');
var TITLE = '<%= j @person_budget_notation.title %>';
var DESCRIPTION = '<%= j @person_budget_notation.description %>';
var AMOUNT = '<%= j @person_budget_notation.amount.to_json %>';
var NOTATION_TYPE = '<%= j @person_budget_notation.notation_type %>';
var ID = '<%= j @person_budget_notation.id.to_json %>';
var fullData;

var currentForm = $('div.content.current > form');
currentForm[0].reset()
// $('.current #sub_budget_notation_notation_type_deposit')[0].value = 'deposit';
// $('.current #sub_budget_notation_notation_type_withdrawal')[0].value = 'withdrawal';

if (flash.messageType == 'danger') {
	console.log("STOPPED!")
} else {

var table = $(' div.content.current > table > tbody');
var content = $('');
if (table.length < 1) {
	fullData = `
		<table class="table table-striped table-condensed">
		    <thead>
		        <tr>
		          <th scope="col">Title</th>
		          <th scope="col" class="hidden-sm hidden-xs">Description</th>
		          <th scope="col">Amount</th>
		          <th scope="col">Action</th>              
		        </tr>
		      </thead>
		      <tbody>
		      	<tr data-id="${ID}" class="type-${NOTATION_TYPE}">
						  <td>${TITLE}</th>
						  <td class="hidden-sm hidden-xs"">${DESCRIPTION}</td>
						  <td>${AMOUNT}</td>
						  <td>
						  	<a class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal" data-remote="true" href="/sub_budget_notations/${ID}/edit">Edit</a>
								<!-- <button type="button" class="btn btn-secondary btn-xs">Delete</button> -->
								<a class="btn btn-danger btn-xs" data-remote="true" rel="nofollow" data-method="delete" href="/sub_budget_notations/${ID}">Delete</a>
						  </td>
						</tr>
		  </tbody>
		</table>
	`;
	$('div.content > p').remove()
	$(fullData).insertAfter('div.content.current #new_sub_budget_notation');

	// FJERNE NO NOTATION!!
}
var data = `
	<tr data-id="${ID}" class="type-${NOTATION_TYPE}">
	  <td>${TITLE}</th>
	  <td class="hidden-sm hidden-xs"">${DESCRIPTION}</td>
	  <td>${AMOUNT}</td>
	  <td>
	  	<a class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal" data-remote="true" href="/sub_budget_notations/${ID}/edit">Edit</a>
			<!-- <button type="button" class="btn btn-secondary btn-xs">Delete</button> -->
			<a class="btn btn-danger btn-xs" data-remote="true" rel="nofollow" data-method="delete" href="/sub_budget_notations/${ID}">Delete</a>
	  </td>
	</tr>
`;

table.append(data);
$(' div.content.current > table').prev()[0].children[1].children[1].focus()
$(' div.content.current').removeClass('current');

}

app/views/person_budget_notations/destroy.js.erb
var ID = '<%= j @person_budget_notation.id.to_json %>';
var current = $("table").find(`tr[data-id=${ID}]`);
var flash = createFlashMessage('<%= j flash[:notice] %>', '<%= j flash[:alert] %>');
$.notify({
    icon: 'pe-7s-trash',
    message: flash.message

  },{
      type: flash.messageType,
      timer: 500
});

current[0].remove();

app/views/person_budget_notations/edit.js.erb
$("#myModal").find('.modal-body').html("<%= j render 'form', person_budget_notation: @person_budget_notation %>");
$("#myModal").modal('show');

var flash = createFlashMessage('<%= j flash[:notice] %>', '<%= j flash[:alert] %>');

$.notify({
    icon: 'pe-7s-flag',
    message: flash.message

  },{
      type: flash.messageType,
      timer: 500
});

app/views/person_budget_notations/update.js.erb
var TITLE = '<%= j @person_budget_notation.title %>';
var DESCRIPTION = '<%= j @person_budget_notation.description %>';
var AMOUNT = '<%= j @person_budget_notation.amount.to_json %>';
var NOTATION_TYPE = '<%= j @person_budget_notation.notation_type %>';
var ID = '<%= j @person_budget_notation.id.to_json %>';
$("#myModal").modal('hide');
var current = $("table").find(`tr[data-id=${ID}]`);

var thTitle = current[0].children[0];
var trDesc = current[0].children[1];
var trAmount = current[0].children[2];
var trType = current[0].children[3];

thTitle.innerHTML = TITLE;
trDesc.innerHTML = DESCRIPTION;
trAmount.innerHTML = AMOUNT;

var flash = createFlashMessage('<%= j flash[:notice] %>', '<%= j flash[:alert] %>');
$.notify({
    icon: 'pe-7s-trash',
    message: flash.message

  },{
      type: flash.messageType,
      timer: 500
});