config/routes.rb
Rails.application.routes.draw do
  get 'members/index'
  get 'members/destroy'
  get 'invitations/index'
  get 'invitations/destroy'

  resources :member_requests
  resources :people
  resources :person_budget_notations
  resources :sub_budgets
  resources :sub_budget_notations
  get 'edit_sub_budget_notation/:id', to: 'sub_budget_notations_controller#edit'
  devise_for :users, :controllers => { :registrations => "user/registrations", :sessions => "sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :family_budgets, only: [:new, :create, :destroy, :show, :edit, :update]
  resources :user_budgets, only: [:create, :destroy]
  get 'search_user', to: 'users#search'
  get 'no_budget', to: 'home#nobudget'
  post 'add_user', to: "users#add_user"
  # post 'invite_user', to: "users#invite_user"
  post 'create_request', to: 'member_requests#create'
  post 'update_request', to: 'member_requests#update'
  post 'delete_request', to: 'member_requests#destroy'
  post 'create_invitation', to: 'invitations#create'
  post 'update_invitation', to: 'invitations#update'
  post 'delete_invitation', to: 'invitations#destroy'
end

app/models/family_budget.rb
class FamilyBudget < ApplicationRecord
  belongs_to :user
  has_many :user_budgets, dependent: :destroy
  has_many :users, through: :user_budgets
  has_many :member_requests
  has_many :people, dependent: :destroy
  has_many :sub_budgets, dependent: :destroy
  has_many :pending_members, through: :member_requests, source: :user
  has_many :invitations, dependent: :destroy
  validates :name, presence: true
  # has_many :memberships, dependent: :destroy
  # has_many :members, through: :memberships
  
  def owner_of_budget
    user = User.find(self.user_id)
    user.full_name
  end

  def total_in_to_budget
  	total_in = 0
  	self.sub_budgets.each do |sb|
  		total_in += sb.incomming
  	end

  	return total_in
  end

  def total_out_from_budget
  	total_out = 0
  	self.sub_budgets.each do |sb|
  		total_out += sb.outgoing
  	end

  	return total_out
  end

  def balance
  	return self.total_in_to_budget - self.total_out_from_budget
  end

  def getAllNotations
    notations = []
    self.sub_budgets.each do |sb|
      sb.sub_budget_notations.each do |sbn|
        notations << sbn
      end
    end

    notations_json = notations.to_json
    return notations_json.html_safe
  end

  def hasOutgoingNotations?
    count = 0
    self.sub_budgets.each do |sb|
      sb.sub_budget_notations.each do |sbn|
        if sbn.notation_type == "withdrawal"
          count += 1
        end
      end
    end
    if count > 0
      return true
    end

    false
  end


end

app/controllers/family_budgets_controller.rb
class FamilyBudgetsController < ApplicationController
	skip_before_action :user_has_budget?, only: [:new, :create]
	def new
		@family_budget = current_user.owner_or_member_of_budget?
		if @family_budget != nil
			puts "\nYou already have a budget\nFuck off!\n\n"
			redirect_to root_path
		end
		@family_budget = FamilyBudget.new
	end
	
	def create
		@family_budget = FamilyBudget.new(budget_params)
		@family_budget.user = current_user
		if @family_budget.save
			puts "success"
			redirect_to root_path
		else
			redirect_to new_family_budget_path
			alertMessage = "Budget was not created! "
   		if @family_budget.errors.messages
   			if @family_budget.errors.messages[:name].present?
   				alertMessage += "You need to specify a name for this budget. "
   			end
   			puts @family_budget.errors.messages
   		end
   		flash[:alert] = alertMessage
		end
	end

	def edit
		@family_budget = FamilyBudget.find(params[:id])
		@members = @family_budget.users
	end

	def update
		@family_budget = FamilyBudget.find(params[:id])
		if @family_budget.update(budget_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def show
		@family_budget = current_user.owner_or_member_of_budget?

		if @family_budget == nil
			puts "\nNo Budget\n\n"
			redirect_to root_path
			return
		end
		
	end

	def destroy
		@family_budget = FamilyBudget.find(params[:id])
		@family_budget.destroy
		redirect_to root_path
	end

	private

	def budget_params
    params.require(:family_budget).permit(:name, :description)
  end

end

app/helpers/family_budgets_helper.rb
module FamilyBudgetsHelper
end

app/views/family_budgets/_form.html.erb
<%= form_for @family_budget do |f| %>
		<div class="form-group">
			<%= f.label :name%>
			<%= f.text_field :name, class: "form-control", placeholder: "Name" %>
		</div>
		<div class="form-group">
			<%= f.label :description%>
			<%= f.text_area :description, class: "form-control", placeholder: "Description"%>
		</div>
		<div class="form-group">
			<%= f.submit class: "btn btn-primary" %>
		</div>
<% end %>

app/views/family_budgets/_lookup.html.erb
<h3>Search for Users</h3>
  <%= form_tag search_user_path, remote: true, method: :get do %>
        <%= text_field_tag :search_param, params[:search_param], placeholder: "Enter name or email", autofocus: true, class: "" %>
        <%= button_tag(type: :submit, class: "btn btn-primary") do %>
          Search
        <% end %>
  <% end %>
<div id="results">
  <%= render 'users/result' %>
</div>

app/views/family_budgets/create.js.erb
var flash = createFlashMessage('<%= j flash[:notice] %>', '<%= j flash[:alert] %>');

$.notify({
    icon: 'pe-7s-flag',
    message: flash.message

  },{
      type: flash.messageType,
      timer: 500
});

app/views/family_budgets/edit.html.erb
<h1>Edit</h1>
<h3>Members of this Family Budget</h3>
<div class="list-group person">
<% @members.each do |member| %>    
  <li data-id="<%= member.id %>" class="list-group-item">
    <p class="list-group-item-text">
    	<strong>Name:</strong> <%= member.full_name ? member.full_name : member.email %>
			<%= link_to "Delete member", user_budget_path(id: member.id), class: "btn btn-danger btn-sm delete-member", remote: true, method: :delete %>
		</p>
  </li>

<% end %>
</div>
<%= render 'form' %>
<% if current_user.family_budget.present? %>
	<%= link_to "Delete Family Budget", family_budget_path(id: current_user.family_budget.id), class: "btn btn-danger btn-lg btn-block",  method: :delete %>
<% end %>

app/views/family_budgets/new.html.erb
<div class="row">
	<div class="col-md-12">
		<h1>New Budget</h1>
		<p>Name it wisely. You only get one. The <strong>Family Budget</strong> is the container for your budgets. In here you create your <strong>Sub Budgets</strong> for every category you need, and add all the <strong>People</strong> involved in the budget.</p>
		<%= render 'form' %>		
	</div>
</div>
<script>
	var flash = createFlashMessage('<%= j flash[:notice] %>', '<%= j flash[:alert] %>');

	$.notify({
	    icon: 'pe-7s-flag',
	    message: flash.message

	  },{
	      type: flash.messageType,
	      timer: 500
	});
</script>

app/views/family_budgets/new.js.erb
var flash = createFlashMessage('<%= j flash[:notice] %>', '<%= j flash[:alert] %>');

$.notify({
    icon: 'pe-7s-flag',
    message: flash.message

  },{
      type: flash.messageType,
      timer: 500
});

app/views/family_budgets/show.html.erb
<h1>Hello</h1>
<%= @family_budget.name %>
<br>
<%= @family_budget.description %>
<br>
<h3>Add someone else to this budget</h3>
<%= render 'users/lookup' %>
<% if current_user.user_budgets.present? %>
	<h3>Leave this budget</h3>
	<%= link_to "Leave Budget", user_budget_path(user_id: current_user.id), method: :delete %>
<% end %>
<h3>Users who want to join this budget</h3>
<ul>
	<% @family_budget.pending_members.each do |request| %>
		<li><%= 
		request.email %>
			<span>
				<%= link_to "Accept membership", update_request_path(request: request, budget: @family_budget.id, user_id: request.id ), method: :post %>
			</span>
		</li>
	<% end %>
</ul>
<br>
<%= link_to "Edit", edit_family_budget_path %>
<%= link_to "Home", root_path %>